# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f58efce70594c827525b4b149879e789a9bd2227dec1f46e08681a6c6f3a7f1ae4ad5f2976e5a14f51f6518db447daef8323fbdbd476da7fc03e2715186d043

test:
  secret_key_base: 112e2e8bbc6214379cc54e47f1cec356d6010fab700687657fb8931c4dcd89d71fe7fa4ac898808897911ade11275eeea287503a54032a6ec9ecc6617cdb061a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
